<?php
/**
 * CommonMetadata automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;

/**
 * @extends \PSX\Record\Record<string>
 */
class CommonMetadata extends \PSX\Record\Record
{
}
