<?php
/**
 * MarketplaceActionCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;


class MarketplaceActionCreate extends MarketplaceAction implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
