<?php
/**
 * MarketplaceBundleSchemaSource automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;

/**
 * @extends \PSX\Record\Record<mixed>
 */
class MarketplaceBundleSchemaSource extends \PSX\Record\Record
{
}
