<?php
/**
 * MarketplaceBundleCreate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;


class MarketplaceBundleCreate extends MarketplaceBundle implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
