<?php
/**
 * MarketplaceAppUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;


class MarketplaceAppUpdate extends MarketplaceApp implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
