<?php
/**
 * MarketplaceDirectoryTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;

use GuzzleHttp\Exception\BadResponseException;
use Sdkgen\Client\Exception\ClientException;
use Sdkgen\Client\Exception\Payload;
use Sdkgen\Client\Exception\UnknownStatusCodeException;
use Sdkgen\Client\TagAbstract;

class MarketplaceDirectoryTag extends TagAbstract
{
    public function app(): MarketplaceDirectoryAppTag
    {
        return new MarketplaceDirectoryAppTag(
            $this->httpClient,
            $this->parser
        );
    }

    public function action(): MarketplaceDirectoryActionTag
    {
        return new MarketplaceDirectoryActionTag(
            $this->httpClient,
            $this->parser
        );
    }


}
