<?php
/**
 * MarketplaceBundleCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;

/**
 * @extends MarketplaceCollection<MarketplaceBundle>
 */
class MarketplaceBundleCollection extends MarketplaceCollection implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
