<?php
/**
 * MarketplaceActionUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;


class MarketplaceActionUpdate extends MarketplaceAction implements \JsonSerializable, \PSX\Record\RecordableInterface
{
}
