<?php
/**
 * MessageException automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Marketplace;

use Sdkgen\Client\Exception\KnownStatusCodeException;

class MessageException extends KnownStatusCodeException
{
    private Message $payload;

    public function __construct(Message $payload)
    {
        parent::__construct('The server returned an error');

        $this->payload = $payload;
    }

    /**
     * @return Message
     */
    public function getPayload(): Message
    {
        return $this->payload;
    }
}
